name: Latest

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ["", -alpine, -centos, -debian]
        flavor: ["", -jre, -jre-headless ]
        version: [ 6, 7, 8, 11, 13, 15, 17, 18 ]
        latest_tag: [ "", -latest ] # FIXME: by README it could be only "-latest"
    steps:
      - uses: actions/checkout@v3
      - run: ./test.sh test_latest ${{matrix.version}} "${{matrix.distro}}" "${{matrix.flavor}}${{matrix.latest_tag}}"
